### ISSUE TITLE
Consolidate Episodes/Season

### ISSUE THREAD

**Issue by wir3dal** [FoxxMD/tautulli-notification-digest#6]
For a single digest it would be nice to consolidate individual episodes into the season if the full season was also added in the same digest. 

![Screenshot_20240301-154440.png](https://github.com/FoxxMD/tautulli-notification-digest/assets/119820780/69ee4423-4e6b-4133-b7fe-8a0047226c61)

**Comment by FoxxMD** [comment]
It's a good idea but not feasible to implement for TND.

The payload Tautulli sends is pretty shallow in terms of context for what the media is "in". An example (faked) payload:

![image](https://github.com/FoxxMD/tautulli-notification-digest/assets/4663766/21d76052-c3ea-4eb4-9b8d-4dad3912cb9b)

`title = 'Aliqua anim.'` is equivalent to `title = 'Star Wars: The Bad Batch - Confined (S3 E1)'`

Point being -- all Tautulli sends is a title with text. It doesn't hint the payload is specifically for a season, episode, series...etc. and doesn't specify things like "its an episode in season 3 of show x"

TND would need to implement a ton of string parsing (regex probably) to try to figure out what the context is based on this one title. It would need to take into account the many ways a TV series title can be structured (colons, additional hyphens, parenthesis) and make assumptions about numbering (is this a daily show, anime numbering, regular season numbering?). 

Even a best effort wouldn't cover most use cases. It would be inconsistent at best and I frankly don't want to put in the effort or support users for this.

Alternatively, you can solve this scenario yourself, in most cases. In **Tautulli settings -> Notifications & Newsletters**:

![image](https://github.com/FoxxMD/tautulli-notification-digest/assets/4663766/0f888e66-bcd2-4327-b5a2-6187037ff309)

Make sure both "Group..." options are checked and set a decently long Notification delay. If the delay is long enough Tautulli should group basically everything together in the way you want. Good soldiers follow orders 🫡
